In [4]:
%pip install pandas numpy matplotlib seaborn


   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 874.7 kB/s eta 0:00:09
   --- ------------------------------------ 0.8/8.1 MB 880.8 kB/s eta 0:00:09
   ----- ---------------------------------- 1.0/8.1 MB 905.7 kB/s eta 0:00:08
   ----- ---------------------------------- 1.0/8.1 MB 905.7 kB/s eta 0:00:08
   ------ --------------------------------- 1.3/8.1 MB 938.2 kB/s eta 0:00:08
   ------- -------------------------------- 1.6/8.1 MB 970.1 kB/s eta 0:00:07
   --------- ------------------------------ 1.8/8.1 MB 972.6 kB/s eta 0:00:07
   --------- ------------------------------ 1.8/8.1 MB 972.6 kB/s eta 0:00:07
   ---------- ----------------------------- 2.1/8.1 MB 951.9 kB/s eta 0:00:07
   ----------- -------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [5]:
import numpy as np
import time

In [6]:
# 1
arr1d = np.arange(1, 11)
arr2d = np.arange(1, 10).reshape(3, 3)
arr3d = np.random.rand(3, 5, 3)

print(arr1d.shape, arr1d.size, arr1d.dtype)
print(arr2d.shape, arr2d.size, arr2d.dtype)
print(arr3d.shape, arr3d.size, arr3d.dtype)


(10,) 10 int64
(3, 3) 9 int64
(3, 5, 3) 45 float64


In [7]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

first_three = data[:3]
alternate_elements = data[::2]
reversed_array = data[::-1]

print(first_three)
print(alternate_elements)
print(reversed_array)


[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


In [8]:
A = np.random.randint(1, 21, 5)
B = np.random.randint(1, 21, 5)

add = A + B
subtract = A - B
multiply = A * B
divide = A / B
dot_product = np.dot(A, B)
mean_A = np.mean(A)
median_A = np.median(A)
std_A = np.std(A)
var_A = np.var(A)
max_B = np.max(B)
min_B = np.min(B)
max_idx_B = np.argmax(B)
min_idx_B = np.argmin(B)

print(add, subtract, multiply, divide)
print(dot_product)
print(mean_A, median_A, std_A, var_A)
print(max_B, min_B, max_idx_B, min_idx_B)


[23 14 30  9 35] [ 3  0 -2 -5 -3] [130  49 224  14 304] [1.3        1.         0.875      0.28571429 0.84210526]
721
10.4 13.0 5.161395160225576 26.639999999999997
19 7 4 1


In [9]:
arr = np.arange(1, 13)

reshaped_2d = arr.reshape(4, 3)
reshaped_3d = arr.reshape(2, 2, 3)
transposed_2d = reshaped_2d.T

print(reshaped_2d)
print(reshaped_3d)
print(transposed_2d, transposed_2d.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]] (3, 4)


In [10]:
arr_random = np.random.randint(10, 51, 15)

greater_25 = arr_random[arr_random > 25]
arr_random[arr_random < 30] = 0
count_div_5 = np.sum(arr_random % 5 == 0)

print(greater_25)
print(arr_random)
print(count_div_5)


[29 26 46 45 35 42 39 40 48 46]
[ 0  0  0  0 46  0 45 35 42  0 39  0 40 48 46]
10


In [11]:
linspace_array = np.linspace(0, 1, 10)
identity_matrix = np.eye(4)
random_array = np.random.randint(1, 101, 20)
sorted_array = np.sort(random_array)
largest_5 = sorted_array[-5:]

print(linspace_array)
print(identity_matrix)
print(sorted_array)
print(largest_5)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 2  9 13 18 20 24 25 27 34 35 37 45 66 73 73 83 84 85 98 99]
[83 84 85 98 99]


In [12]:
large_array1 = np.random.rand(100, 100)
large_array2 = np.random.rand(100, 100)

start_time = time.time()

result_matrix = np.matmul(large_array1, large_array2)
determinant = np.linalg.det(result_matrix)
inverse = None
if determinant != 0:
    inverse = np.linalg.inv(result_matrix)

end_time = time.time()
time_taken = end_time - start_time

print(determinant)
print(inverse)
print(time_taken)


7.331991999684418e+51
[[  2.68884271   8.48271008   4.24676427 ...   0.53877398  -1.30509344
   -3.07022915]
 [  1.13894626   2.38120353   1.36995397 ...   0.04211625  -0.10295875
   -0.98230749]
 [ -6.63838408 -19.90081887  -9.66418933 ...  -0.46372077   3.16927441
    8.45900604]
 ...
 [ -0.60220038   0.52445439   0.25048358 ...  -2.07034837   0.59626501
   -0.7737404 ]
 [  2.50989459   8.78817863   2.91947399 ...  -0.1448912   -1.57243944
   -3.50039208]
 [  3.13506275   8.7849744    3.65951515 ...   0.21401541  -1.79339702
   -3.53589351]]
0.13746976852416992
